# Generated by Django 3.1.5 on 2025-01-23 07:25

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('date', models.DateTimeField(verbose_name='比赛时间')),
                ('location', models.CharField(max_length=100, verbose_name='比赛地点')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('ongoing', '进行中'), ('finished', '已结束')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': '比赛项目',
                'verbose_name_plural': '比赛项目',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='团队名称')),
                ('score', models.IntegerField(default=0, verbose_name='团队总分')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('judge', '裁判员'), ('athlete', '运动员')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='athletic_users', related_query_name='athletic_user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='athletic_users', related_query_name='athletic_user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='成绩')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('is_quit', models.BooleanField(default=False, verbose_name='是否弃权')),
                ('confirmed', models.BooleanField(default=False, verbose_name='成绩是否确认')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='athletic_system.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletic_system.event')),
            ],
            options={
                'verbose_name': '比赛成绩',
                'verbose_name_plural': '比赛成绩',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='judges',
            field=models.ManyToManyField(limit_choices_to={'role': 'judge'}, related_name='judging_events', to='athletic_system.User'),
        ),
    ]
