# Generated by Django 3.1.5 on 2025-01-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='职称')),
                ('specialty', models.CharField(max_length=100, verbose_name='专长项目')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'judge'}, on_delete=django.db.models.deletion.CASCADE, to='athletic_system.user')),
            ],
            options={
                'verbose_name': '裁判员',
                'verbose_name_plural': '裁判员',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletic_system.team', verbose_name='所属团队')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, to='athletic_system.user')),
            ],
            options={
                'verbose_name': '运动员',
                'verbose_name_plural': '运动员',
            },
        ),
    ]
