# Generated by Django 3.1.5 on 2025-01-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_system', '0002_athlete_judge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': '比赛项目', 'verbose_name_plural': '比赛项目'},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=0, verbose_name='最大参赛人数'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报名截止时间'),
        ),
        migrations.AddField(
            model_name='result',
            name='quit_reason',
            field=models.TextField(blank=True, verbose_name='弃权原因'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('judge', '裁判员'), ('athlete', '运动员')], default='admin', max_length=10),
        ),
    ]
