# Generated by Django 5.1.3 on 2025-03-12 03:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_system', '0003_auto_20250123_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='身高(cm)'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在籍'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='体重(kg)'),
        ),
        migrations.AddField(
            model_name='judge',
            name='experience_years',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='从业年限'),
        ),
        migrations.AddField(
            model_name='judge',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='是否可排班'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(30)], verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], db_index=True, max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='athletic_system.team', verbose_name='所属团队'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'judge'}, on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='athlete',
            field=models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='运动员'),
        ),
        migrations.AlterField(
            model_name='result',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletic_system.event', verbose_name='比赛'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')]),
        ),
    ]
