# Generated by Django 5.1.3 on 2025-03-23 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_system', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), verbose_name='比赛持续时间'),
        ),
    ]
