# Generated by Django 5.1.3 on 2025-04-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_system', '0006_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='height',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='experience_years',
        ),
    ]
